### ISSUE TITLE
Wrongly set up wmo_boxes

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#3]
I set my wmo_boxes_test.mat to have all columns responsible for selecting reference data (CTD, bottle and Argo) to be 0.
During running update_salinity_mapping routine, I obtained the below error.

`UPDATE_SALINITY_MAPPING: Working on profile  0
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_SSH/owc-software-python/owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 294, in update_salinity_mapping
    if grid_lat.__len__() > 0:
AttributeError: 'int' object has no attribute '__len__'

Process finished with exit code 1
`

I found that the grid_lat value is 999. This means that the code can not find any data from the reference data. 

Float source: 3901960.mat
WMO boxes: wmo_boxes_test.m (testing matrix with all values with 1 turned to 0)
config:
`        # ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.5,
        'MAPSCALE_PHI_SMALL': 0.1,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 10,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 200,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 250`

**Comment by edsmall-bodc** [comment]
In the matlab version if we retrieve no data from the wmo_boxes the function returns some data that will never be used (since 999 latitude and longitude do not exist). This seems to have been done so that the program doesn't crash.

However, this is probably not a sustainable solution, for 2 reasons: 

1. It causes a pretty poorly explained error that doesn't really describe the problem
2. If we are getting literally 0 data for a float then we should not proceed with the analysis since literally no analysis can be done.

As you have pointed out, this is most commonly going to occur when an operator accidentally sets all the WMO box values to 0, thus asking for no data. 

I propose that, instead of offering unusable values, we create a custom error message advising the operator to check the WMO box matrix and halt the process there.

**Comment by edsmall-bodc** [comment]
Fixed in https://git.noc.ac.uk/bodc/owc-software-python/-/merge_requests/28

Test has been written to check that if get_hist_region_locations gathers no data that an error is raise telling the user. It also suggest that the user check their WMO matrix, as we expect this to commonly occur if all values are set to 0.

Closing the issue
