### ISSUE TITLE
problem with tbase_decoder?

### ISSUE THREAD

**Issue by cabanesc** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#9]
Hi Ed,

I run the owc_calibration.py for a deep float (6902881) that I have just DMQCed.
I am using CTD boxes only from CTD_for_DMQC_2019VO1 

Source file and configuration file are here:
[6902881_test1.tar.gz](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4645000/6902881_test1.tar.gz)

I got a warming on profile#0 and an error on profile #54 

UPDATE_SALINITY_MAPPING: Working on profile  0
/home1/homedir5/perso/ccabanes/dvlpRD/Argo/owc-software-python/ow_calibration/interp_climatology/interp_climatology.py:118: RuntimeWarning: invalid value encountered in less
  grid_theta_below_pres = np.argwhere(tst[delta_pres_min_index[j]:grid_level] < 0)
  
...

UPDATE_SALINITY_MAPPING: Working on profile  54
Traceback (most recent call last):
  File "owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/owc-software-python/ow_calibration/update_salinity_mapping/update_salinity_mapping.py", line 304, in update_salinity_mapping
    np.amax(grid_lat) + 1)
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/owc-software-python/ow_calibration/tbase_decoder/tbase_decoder.py", line 70, in get_topo_grid
    elev_file.seek((i + decoder[3]) * 360 * 12 * 2 + decoder[0] * 2)
OSError: [Errno 22] Invalid argument
6001.981u 226.270s 28:16.46 367.1%      0+0k 81592+8io 0pf+0w

Cecile

**Comment by edsmall-bodc** [comment]
I will see if I can reproduce when we move to the next phase and get back to you. I assume this ran fine in the matlab version?

One of my major concerns was the t-base decoder because I had to reverse engineer it, and had very limited resources to check it was absolutely perfect, thought I tested it as much as was feasible. I would have been shocked if it didn't break at some point.

It must be accessing a line in the file that is inaccessible (most likely because the line does not exist). If this is the case, there is a possibility it is spitting out some other bad values, but it might be hard to notice because they are close but not quite correct but still feasible.

@kamwal. this could be why we found a value that was out of tolerance. The interpolations would be thrown off because we would have incorrect z values. I may need your help debugging this slightly.

I will go over this with a fine tooth comb next phase and report back. My initial thoughts are to save the outputs from the matlab and python version and find where values start to deviate. From there I can step through with the debugger.

Thank you for reporting it to me.

The warning is nothing to worry about - you will probably get it every time you run the program. Python complains when you compare NaNs (eg in an if statement)

**Comment by edsmall-bodc** [comment]
@cabanesc do you mind just copy and pasting your objective parameters here too? Just to be sure that when I try and reproduce the bug we have the same settings

**Comment by cabanesc** [comment]
# ===============================
        #
        #    Constants File Path
        #

        'CONFIG_DIRECTORY': "data/constants/",
        'CONFIG_COASTLINES': "coastdat.mat",
        'CONFIG_WMO_BOXES': "wmo_boxes_ctd.mat",
        'CONFIG_SAF': "TypicalProfileAroundSAF.mat",

        # ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 250,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 3.2,
        'MAPSCALE_LONGITUDE_SMALL': 2,
        'MAPSCALE_LATITUDE_LARGE': 2,
        'MAPSCALE_LATITUDE_SMALL': 1,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.01,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 2,
        'MAPSCALE_AGE_SMALL': 0.69,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 200,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 250
    }

**Comment by edsmall-bodc** [comment]
Thank you!

**Comment by kamwal** [comment]
The issue with t_base decoder has been fixed using the [fix](https://github.com/euroargodev/argodmqc_owc/pull/52)
